#!/bin/sh

gencommon () {
	dep="build/${s%.*}${1}.d"
	obj="build/${s%.*}${1}"
	
	mkdir -p $(dirname ${dep})

	echo "${dep}:"		>> deps.mk
	echo "include ${dep}"	>> deps.mk
	echo "${obj}: ${s}"		>> deps.mk

}
genlink () {
	gencommon ".ld"
	echo "	\$(GENLINK) $< | \$(STRIPLINK) > \$@"	>> deps.mk
}

genrule () {
	gencommon "${1}"
	echo "	\$(COMPILE) ${defs} -c \$< -o \$@"	>> deps.mk
}

case "${1}" in
	--kern)
		suffix=.k.o
		defs=-DKERNEL
		func=genrule
		;;
	--init)
		suffix=.i.o
		defs=-DINIT
		func=genrule
		;;
	--link)
		suffix=.ld
		func=genlink
		;;
esac

for s in ${2}
do
	${func} ${suffix}
	echo ${obj}
done
