#!/bin/sh

mkdir -p $(for d in "${@}"; do echo $d; done | sed "s|^|build/|")
mkdir -p $(for d in "${@}"; do echo $d; done | sed "s|^|reports/|")

for NAME in "${@}"; do cat << ENDRULES >> tests.mk
build/$NAME/init.d:
-include build/$NAME/init.d

build/$NAME/init: $NAME/init.c \$(COMMON) \$(KMI)
	\$(COMPILE_TEST) $NAME/init.c \$(COMMON) -o build/$NAME/init

build/$NAME/initrd: build/$NAME/init
	echo build/$NAME/init | \$(GEN_INITRD) build/$NAME/initrd

reports/$NAME/log: build/$NAME/initrd
	timeout --foreground 30s \$(QEMU) build/$NAME/initrd > reports/$NAME/log

TESTS += $NAME
.PHONY: $NAME
$NAME: reports/$NAME/log

ENDRULES
done
